FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server ./cmd/app/

# Финальный образ
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/server /app/server

COPY config config

CMD ["./server"]