FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o migrate ./cmd/migrator

# Финальный образ
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/migrate /app/migrate

COPY config config

COPY migrations migrations

CMD ["./migrate"]